spring:
  application:
    name: 26_SBMS_CUSTOM_PK
  
  
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/emp
    username: postgres
    password: nic@123
    
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true       